FROM abeja/base:19.10

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3.7 \
    python3.7-dev \
    python3-pip && \
    wget -O ~/get-pip.py https://bootstrap.pypa.io/get-pip.py && \
    python3.7 ~/get-pip.py

RUN ln -sf /usr/bin/python3.7 /usr/local/bin/python3 && \
    ln -sf /usr/bin/python3.7 /usr/local/bin/python && \
    python -m pip --no-cache-dir install --upgrade setuptools
