FROM abeja/base:19.10

RUN python -m pip --no-cache-dir install --upgrade numpy
RUN python -m pip --no-cache-dir install --upgrade --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html

# If it is not installed correctly, the build will fail.
# You can comment out if you don't need it.
RUN python -c "import torch ;x = torch.rand(5, 3) ;print(x) "
