FROM abeja/base-cuda100:19.10

RUN python -m pip --no-cache-dir install --upgrade tensorflow-gpu==2.0.0

# If it is not installed correctly, the build will fail.
# You can comment out if you don't need it.
# and To use a GPU, Docker default runtime must be nvidia.
RUN python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
RUN nvidia-smi
RUN python -c 'from tensorflow.python.client import device_lib; device_lib.list_local_devices()'
